### ISSUE TITLE
Implement multisite:provision

### ISSUE THREAD

**Issue by richardbporter** [uiowa/multisite#1]
Temporary provisioning is handled via its-uofiowa/drupal-manifest. 

Once resolved, provisioning should:
- [x] Be invoked locally
- [x] Insert multisite record into `manifest.yml` in new manifest repo (https://github.com/uiowa/drupal-manifest)
  - Record should include machine-consumable metadata like profile, git repo, redirects, technical contact email, customer contact name & email (i.e., site owner), etc.
- ~~~Update existing records, if they exist.~~~
  - This can be done manually.
- [x] Run a pipelines build in the appropriate environment(s).
- [x] Run the installation profile through Drush in one environment and sync, if necessary.

Questions
- The above would allow individual sites to be provisioned per environment.
  - This will still be possible with new domains key in manifest.

**Comment by genjohnson** [comment]
I've added `technical contact email, customer contact name & email (i.e., site owner)` to the metadata list. In the long run this information may be handled with a CRM solution, but we need somewhere to store the info for now and the manifest table seems like an okay place.

I think allowing individual sites to be provisioned per environment is desirable. Right now we have a dev, stage and prod install for every standard site when all we really need is the prod install, so this causes us some over head when running updates.
