### ISSUE TITLE
provision: git option should just use the URI

### ISSUE THREAD

**Issue by richardbporter** [uiowa/multisite#26]
For simplicity.

**Comment by richardbporter** [comment]
@genjohnson What do think of this? Just to simplify the command to: `drush msp foo.com --git`

**Comment by genjohnson** [comment]
That would be awesome! And a different repo name could be specified if necessary?

**Comment by genjohnson** [comment]
Actually, would we even still need to pass `--git` if we want to just use the URI? Would it be possible to only need to use `--git` if you wanted to specify a repo name that's NOT the URI?

**Comment by richardbporter** [comment]
No I was thinking we don’t have that use case but maybe we do?

-----------------------
Richard B. Porter
ITS Web Services
2800 UCC
(319) 467-1113

**Comment by genjohnson** [comment]
When sites change URI (like ip.uiowa.edu -> international.uiowa.edu), is it necessary to change the name of the repo? That's the only case I can think of we've run into where the URI and repo name might not be the same.
