### ISSUE TITLE
generate: Clarify nothing is wrong when repository already exists

### ISSUE THREAD

**Issue by genjohnson** [uiowa/multisite#35]
When multisite:generate` tries to clone the repository for each site, if a repository has previously been cloned then a notice like `Cannot clone eight.uiowa.edu repository. Destination path <path to site> already exists.` is returned.

To me, `Cannot clone` sounds like something went wrong - that the repository should have been cloned but could not be because the destination path already exists.

I propose the wording of this message be changed to more clearly indicate that the repository has already been cloned and that all is okay.

**Comment by richardbporter** [comment]
Thanks!
