### ISSUE TITLE
generate: warnings related to drush aliases

### ISSUE THREAD

**Issue by richardbporter** [uiowa/multisite#58]
[warning] Invalid argument supplied for foreach() MultisiteCommands.php:375
 [warning] file_get_contents(/app/drush/sites/dev.site.yml): failed to open stream: No such file or directory MultisiteCommands.php:396
 [warning] file_get_contents(/app/drush/sites/test.site.yml): failed to open stream: No such file or directory MultisiteCommands.php:396
 [warning] file_get_contents(/app/drush/sites/prod.site.yml): failed to open stream: No such file or directory MultisiteCommands.php:396

**Comment by pyrello** [comment]
Getting this message when running `lando start`

**Comment by pyrello** [comment]
I am wondering if this is related to the fact that the containers on Acquia Cloud that I have access to don't have any D8 sites?

The invalid argument being supplied to foreach is NULL, which is happening on this line: 

`$aliases = $drushrc->{"prod:{$app}"};`

https://github.com/uiowa/multisite/blob/master/MultisiteCommands.php#L369
